# Generated by Django 6.0.1 on 2026-03-23 23:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0002_emergencyalert_user_ambulancedriver_victim_volunteer"),
    ]

    operations = [
        migrations.AddField(
            model_name="hospital",
            name="has_antivenom",
            field=models.BooleanField(default=True),
        ),
    ]
