# Generated by Django 6.0.1 on 2026-03-24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0003_hospital_has_antivenom"),
    ]

    operations = [
        migrations.AddField(
            model_name="emergencyalert",
            name="assigned_driver",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="api.ambulancedriver",
            ),
        ),
        migrations.AddField(
            model_name="emergencyalert",
            name="assigned_hospital",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="api.hospital",
            ),
        ),
        migrations.AddField(
            model_name="emergencyalert",
            name="assigned_volunteer",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="api.volunteer",
            ),
        ),
        migrations.AddField(
            model_name="emergencyalert",
            name="has_vehicle",
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="emergencyalert",
            name="patient_phone",
            field=models.CharField(blank=True, max_length=15),
        ),
        migrations.AddField(
            model_name="emergencyalert",
            name="status",
            field=models.CharField(
                choices=[
                    ("pending", "Pending"),
                    ("hospital_routed", "Hospital Routed"),
                    ("ambulance_notified", "Ambulance Notified"),
                    ("ambulance_accepted", "Ambulance Accepted"),
                    ("volunteer_notified", "Volunteer Notified"),
                    ("completed", "Completed"),
                ],
                default="pending",
                max_length=30,
            ),
        ),
    ]
